### PR TITLE
Nvidia 384.111

### PR DESCRIPTION
**Pull request by eszlari**
This version just got uploaded to Ubuntu 17.10.

### CODE REVIEW

**Comment by alexlarsson** [comment]
I'm very sorry, but this is the wrong place, can you file it against https://github.com/flatpak/freedesktop-sdk-images/tree/nvidia-drivers instead? (And then i can delete this repo)

**Comment by eszlari** [comment]
Okay, sorry, I will do that, but why is this repo mentioned here:

https://github.com/flathub/buildbot-config/blob/master/builds.json#L20

Maybe you could document the nvidia update process somewhere public, because it affects nvidia users like myself very much (I can't start flatpaks on my main computer anymore).

**Comment by alexlarsson** [comment]
Ah, that was just used for early testing when redoing the nvidia build setup. I'll remove that too.

**Comment by eszlari** [comment]
Done: https://github.com/flatpak/freedesktop-sdk-images/pull/73

**Pull request closed without merging**
